### ISSUE TITLE
Macro Anchor miss-splaced

### ISSUE THREAD

**Issue by ndufresne** [MathieuDuponchelle/better_doctool#1]
https://people.collabora.com/~meh/gst_doc_new/gst/GstEvent.html#gst_event_make_writable

This align to the blue box. I think it should display "The “gst_event_make_writable” function macro". Applies to all macro of course.

**Comment by MathieuDuponchelle** [comment]
Fixed by de3508b6af9debe5bdeacfe2ccb5452ef766b23a , thanks
