### ISSUE TITLE
Some link to enumeration member are broken

### ISSUE THREAD

**Issue by ndufresne** [MathieuDuponchelle/better_doctool#2]
https://people.collabora.com/~meh/gst_doc_new/gst/GstEvent.html#GST_EVENT_TYPE_BOTH

If you click on GST_EVENT_TYPE_UPSTREAM or GST_EVENT_TYPE_DOWNSTREAM it does nothing.

**Comment by MathieuDuponchelle** [comment]
Fixed by 0d2af881952835eb5dc519b7bf01fe5169cabb3c , thanks !
