### ISSUE TITLE
Sometimes constants includes unwanted trailing character (like \)

### ISSUE THREAD

**Issue by ndufresne** [MathieuDuponchelle/better_doctool#3]
I'm not sure what is the right thing to do here. Though when a constant is like

#define FOO \
    VALUE

Then the doc will show FOO \, in GTK doc it will strip \, which is probably the cleanest minimalist approach.

Example:
https://people.collabora.com/~meh/gst_doc_new/gst/GstEvent.html#GST_EVENT_TYPE_BOTH

**Comment by MathieuDuponchelle** [comment]
Fixed the correct way by e53654b59327e0d8d9dec9ad1d1566e25db54cca , gtk-doc doesn't handle multi-line macros very well, the full extent of the macro should be extracted from the source IMHO
