### ISSUE TITLE
Link to types shall bring to the type page instead of the struct

### ISSUE THREAD

**Issue by ndufresne** [MathieuDuponchelle/better_doctool#4]
This use to be a problem in GTK Doc too, but it not it seems. Basicallyin GTK Doc we do #GstStructure and expect to reach:

https://people.collabora.com/~meh/gst_doc_new/gst/GstStructure.htm

Right now (maybe it's a conversion bug, I don't know) we reach this:

https://people.collabora.com/~meh/gst_doc_new/gst/GstStructure.html#GstStructure

**Comment by MathieuDuponchelle** [comment]
Also fixed by de3508b6af9debe5bdeacfe2ccb5452ef766b23a it seems :)
